// import { Geist, Geist_Mono } from "next/font/google";
import { Ubuntu } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const ubuntu = Ubuntu({
  weight: ["400", "500", "700"], // choose the weights you need
  subsets: ["latin"],
  variable: "--font-ubuntu", // ✅ make it available as a CSS variable
});


export const metadata = {
  title: "CareCompanioinAI | Team Zero",
  description: "Generated by Team Zero",
  icons: {
    icon: "/logo.png", // or "/logo.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
